### ISSUE TITLE
Tutorials in English (broken link - 404)

### ISSUE THREAD

**Issue by gurpreet-hanjra** [LekoArts/portfolio#12]
Hello, I was browsing your portfolio and wanted to check the tutorials in English. But somehow I think they are not available in English. May be showing message like `Tutorials not available in English` or something like this. 

https://www.lekoarts.de/en/categories/tutorial

btw, great website and interesting content on your site!

Thank you!

**Comment by LekoArts** [comment]
I translated one of my older tutorials to have some content. I was aware of this situation but didn't have time. Thanks for the notice :)
