### ISSUE TITLE
GraphQL Error Unknown type "PrismicBlogpost".

### ISSUE THREAD

**Issue by neuyu** [LekoArts/portfolio#144]
where should i set process.env.API_KEY

**Comment by LekoArts** [comment]
Hi!
This repository is not intended for usage outside of my own site hence it's not a template. The API_KEY is referring to my Prismic API key.

You can have a look at my Gatsby starters if you need a project:
https://gatsby-starter-portfolio.netlify.com/

Have a nice day! :)
